(function(a){a.AudioContext=a.AudioContext||a.webkitAudioContext;this.that=this;var b=b||function(a){a=a||500;b.oscillator.connect(b.context.destination);b.oscillator.start(0);setTimeout(function(){b.oscillator.disconnect()},a)};b.context=b.context||new AudioContext;b.oscillator=b.oscillator||b.context.createOscillator();b.oscillator.type=1;this.beep=b}).call(this,window);
(function(a,b){if("object"===typeof exports&&exports)b(exports);else{var m={};b(m);"function"===typeof define&&define.amd?define(m):a.Mustache=m}})(this,function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function m(a){this.tail=this.string=a;this.pos=0}function n(a,c){this.view=a||{};this.parent=c;this._cache={}}function k(){this.clearCache()}function p(u,c,f,g){for(var d="",b,e,m=0,k=u.length;m<k;++m)switch(b=u[m],e=b[1],b[0]){case "#":e=f.lookup(e);if("object"===typeof e)if(w(e))for(var q=
0,h=e.length;q<h;++q)d+=p(b[4],c,f.push(e[q]),g);else e&&(d+=p(b[4],c,f.push(e),g));else"function"===typeof e?(b=null==g?null:g.slice(b[3],b[5]),e=e.call(f.view,b,function(a){return c.render(a,f)}),null!=e&&(d+=e)):e&&(d+=p(b[4],c,f,g));break;case "^":e=f.lookup(e);if(!e||w(e)&&0===e.length)d+=p(b[4],c,f,g);break;case ">":e=c.getPartial(e);"function"===typeof e&&(d+=e(f));break;case "&":e=f.lookup(e);null!=e&&(d+=e);break;case "name":e=f.lookup(e);null!=e&&(d+=a.escape(e));break;case "text":d+=e}return d}
function v(a){return[RegExp(b(a[0])+"\\s*"),RegExp("\\s*"+b(a[1]))]}var z=/\s*/,x=/\s+/,A=/\S/,y=/\s*=/,B=/\s*\}/,C=/#|\^|\/|>|\{|&|=|!/,D=RegExp.prototype.test,E=Object.prototype.toString,w=Array.isArray||function(a){return"[object Array]"===E.call(a)},F={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"};m.prototype.eos=function(){return""===this.tail};m.prototype.scan=function(a){return(a=this.tail.match(a))&&0===a.index?(this.tail=this.tail.substring(a[0].length),this.pos+=
a[0].length,a[0]):""};m.prototype.scanUntil=function(a){var c=this.tail.search(a);switch(c){case -1:a=this.tail;this.pos+=this.tail.length;this.tail="";break;case 0:a="";break;default:a=this.tail.substring(0,c),this.tail=this.tail.substring(c),this.pos+=c}return a};n.make=function(a){return a instanceof n?a:new n(a)};n.prototype.push=function(a){return new n(a,this)};n.prototype.lookup=function(a){var c=this._cache[a];if(!c){if("."==a)c=this.view;else for(var f=this;f;){if(0<a.indexOf("."))for(var c=
f.view,b=a.split("."),d=0;c&&d<b.length;)c=c[b[d++]];else c=f.view[a];if(null!=c)break;f=f.parent}this._cache[a]=c}"function"===typeof c&&(c=c.call(this.view));return c};k.prototype.clearCache=function(){this._cache={};this._partialCache={}};k.prototype.compile=function(b,c){var f=this._cache[b];f||(f=a.parse(b,c),f=this._cache[b]=this.compileTokens(f,b));return f};k.prototype.compilePartial=function(a,c,b){c=this.compile(c,b);return this._partialCache[a]=c};k.prototype.getPartial=function(a){a in
this._partialCache||!this._loadPartial||this.compilePartial(a,this._loadPartial(a));return this._partialCache[a]};k.prototype.compileTokens=function(a,c){var b=this;return function(g,d){if(d)if("function"===typeof d)b._loadPartial=d;else for(var l in d)b.compilePartial(l,d[l]);return p(a,b,n.make(g),c)}};k.prototype.render=function(a,c,b){return this.compile(a)(c,b)};a.name="mustache.js";a.version="0.7.2";a.tags=["{{","}}"];a.Scanner=m;a.Context=n;a.Writer=k;a.parse=function(u,c){u=u||"";c=c||a.tags;
"string"===typeof c&&(c=c.split(x));if(2!==c.length)throw Error("Invalid tags: "+c.join(", "));for(var f=v(c),g=new m(u),d=[],l=[],e=[],k=!1,n=!1,q,h,r,p;!g.eos();){q=g.pos;if(r=g.scanUntil(f[0])){p=0;for(var t=r.length;p<t;++p)if(h=r.charAt(p),D.call(A,h)?n=!0:e.push(l.length),l.push(["text",h,q,q+1]),q+=1,"\n"==h){if(k&&!n)for(;e.length;)delete l[e.pop()];else e=[];n=k=!1}}if(!g.scan(f[0]))break;k=!0;h=g.scan(C)||"name";g.scan(z);"="===h?(r=g.scanUntil(y),g.scan(y),g.scanUntil(f[1])):"{"===h?(r=
g.scanUntil(RegExp("\\s*"+b("}"+c[1]))),g.scan(B),g.scanUntil(f[1]),h="&"):r=g.scanUntil(f[1]);if(!g.scan(f[1]))throw Error("Unclosed tag at "+g.pos);p=[h,r,q,g.pos];l.push(p);if("#"===h||"^"===h)d.push(p);else if("/"===h){if(0===d.length)throw Error('Unopened section "'+r+'" at '+q);h=d.pop();if(h[1]!==r)throw Error('Unclosed section "'+h[1]+'" at '+q);}else if("name"===h||"{"===h||"&"===h)n=!0;else if("="===h){c=r.split(x);if(2!==c.length)throw Error("Invalid tags at "+q+": "+c.join(", "));f=v(c)}}if(h=
d.pop())throw Error('Unclosed section "'+h[1]+'" at '+g.pos);for(var f=l,g=[],s,l=0,e=f.length;l<e;++l)if(d=f[l])"text"===d[0]&&s&&"text"===s[0]?(s[1]+=d[1],s[3]=d[3]):(s=d,g.push(d));s=g;g=f=[];d=[];e=0;for(k=s.length;e<k;++e)switch(l=s[e],l[0]){case "#":case "^":d.push(l);g.push(l);g=l[4]=[];break;case "/":d.pop()[5]=l[2];g=0<d.length?d[d.length-1][4]:f;break;default:g.push(l)}return f};a.escape=function(a){return String(a).replace(/[&<>"'\/]/g,function(a){return F[a]})};var t=new k;a.clearCache=
function(){return t.clearCache()};a.compile=function(a,c){return t.compile(a,c)};a.compilePartial=function(a,c,b){return t.compilePartial(a,c,b)};a.compileTokens=function(a,b){return t.compileTokens(a,b)};a.render=function(a,b,f){return t.render(a,b,f)};a.to_html=function(b,c,f,g){b=a.render(b,c,f);if("function"===typeof g)g(b);else return b}});var app=app||{};app.templates=app.templates||{};app.templates.alarm='<div class="alarm" data-id="{{id}}"><div class="symbol-wrapper"><div class="symbol">{{type}}</div></div><div class="alarm-text">${{price}}</div><div class="delete button">delete</div></div>';
app.templates.modal='<div class="curtain"><div class="modal"><header>Alarm Started</header><div class="inner">The price moved past your alarm set at ${{price}}.<div class="stop-alarm button">stop alarm</div></div></div></div>';app=app||{};app.config={currency:"USD"};app.url="http://data.mtgox.com/api/2/BTC"+app.config.currency+"/money/ticker_fast?pretty";
app.models={alarms:{data:[],get:function(){return app.models.alarms.data},remove:function(a){for(var b=0,m=app.models.alarms.data.length;b<m;b++)if(app.models.alarms.data[b]&&app.models.alarms.data[b].id===a){delete app.models.alarms.data[b];break}},save:function(){var a={id:Date.now(),type:$(".alarm-option.active").data("type"),price:$(".price-threshold").val()};app.models.alarms.data.push(a);return a}},price:{data:{now:{value:"181.08013",value_int:"18108013",display:"$181.08"}},get:function(){return app.models.price.data.now},
getLast:function(){return app.models.price.data.last},update:function(){$.get(app.url,function(a){a=a.data.last_local;app.models.price.data.last=app.models.price.data.last?app.models.price.data.now:a;app.models.price.data.now=a;app.gotPrice(app.models.price.data.now)})}}};
app.views={alarms:{display:function(a){a=Mustache.compile(app.templates.alarm)(a);$(".alarms-set").prepend(a)},remove:function(a){$('.alarm[data-id="'+a+'"]').remove()},activate:function(a){$('.alarm[data-id="'+a+'"]').addClass("active")},deactivate:function(a){$('.alarm[data-id="'+a+'"]').removeClass("active")},deactivateAll:function(){$(".alarm.active").removeClass("active")}},price:{display:function(a){$("#price").text(a)}},modal:{display:function(a){a=Mustache.compile(app.templates.modal)({price:a});
$("body").append(a);setTimeout(function(){$(".curtain").addClass("active")},1)}}};app.updatePrice=setInterval(app.models.price.update,5E3);app.showModal=function(a){app.views.modal.display(a)};app.closeModal=function(){$(".curtain").removeClass("active");setTimeout(function(){$(".curtain").remove()},200);app.stopAlarm()};app.soundAlarm=function(a){app.showModal(a.price);app.views.alarms.activate(a.id);app.startAlarm()};app.startAlarm=function(){app.alarm=setInterval(beep,600)};
app.stopAlarm=function(){console.log("STOPPING ALARM");clearInterval(app.alarm);app.alarm=!1;app.views.alarms.deactivateAll()};app.gotPrice=function(a){app.views.price.display(a.display);app.checkAlarms()};app.setAlarm=function(){var a=app.models.alarms.save(),b=this;app.views.alarms.display(a);$(this).addClass("active");setTimeout(function(){$(b).removeClass("active")},1E3)};app.setType=function(){$(".alarm-option.active").removeClass("active");$(this).addClass("active")};
app.clickDelete=function(){var a=$(this).parents(".alarm").data("id");app.models.alarms.remove(a);app.views.alarms.remove(a)};app.checkAlarms=function(){if(!app.alarm)for(var a=app.models.alarms.get(),b=0,m=a.length;b<m;b++)if(a[b]){var n=a[b],k=parseFloat(n.price),p=parseFloat(app.models.price.get().value),v=parseFloat(app.models.price.getLast().value);if(k>=p&&k<v||k<=p&&k>v){app.runAlarm(n);break}}};
app.runAlarm=function(a){"alarm"===a.type?app.soundAlarm(a):(a.type="one beep",app.views.alarms.activate(a.id),beep(),setTimeout(function(){app.views.alarms.deactivate(a.id)},400))};
$(document).ready(function(){app.gotPrice(app.models.price.get());app.models.price.update();$(".set-alarm").click(app.setAlarm);$(".price-threshold").keypress(function(a){13===a.keyCode&&app.setAlarm()});$(".alarm-option").click(app.setType);$(".alarms").on("click",".delete",app.clickDelete);$("body").on("click",".curtain",app.closeModal)});